### ISSUE TITLE
Custom domains on GitHub Pages now support HTTPS directly

### ISSUE THREAD

**Issue by spaze** [pehapkari/pehapkari.cz#452]
Update this [post about HTTPS via Cloudflare](https://github.com/pehapkari/pehapkari.cz/blob/master/source/_posts/2017/2017-03-13-how-to-add-https-to-github-pages-in-6-steps.md) to say that it's possible to use HTTPS directly.

Also add a howto for going back from Cloudflare to Github's native HTTPS.

And maybe, just maybe, move the pehapkari.cz/sk site off Cloudflare to use the option, too.

**Comment by TomasVotruba** [comment]
I just tried going Github only on https://github.com/tomasvotruba/tomasvotruba.cz and the Github tutorial was so complicated and unclear that I gave up after 6 hours and went back to Cloudflare.

Used sources:

- https://blog.github.com/2018-05-01-github-pages-custom-domains-https/
- https://help.github.com/articles/setting-up-an-apex-domain/

WTF foundings:

- to enable https, Github needs to be pinged by deleting then readding `CNAME`
- there is different `www` setup than Cloudflare, also the `CNAME` and domain in repository settings needs to be without `www.`, otherwise the `https://` option on Github is disabled

**Comment by TomasVotruba** [comment]
Closing as I'm unable to resolve it and current `https://` works.

**Comment by spaze** [comment]
Changed the post to say the CF method is deprecated
